--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Estem02/ChangeProtocol
build-by-default: true
branches:
- main
projects:
  ChangeProtocol:
    path: "https://br.freepik.com/vetores-gratis/ilustracao-interruptor-setas_2606151.htm#query=Icone%20Change&position=0&from_view=search"
...
